language: c
sudo: false
services:
  - docker
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-docker.sh
script: bash -ex ./.travis-docker.sh
env:
  global:
  - PINS="dataloader:. dataloader-lwt:."
  matrix:
  - PACKAGE="dataloader" DISTRO="ubuntu-16.04" OCAML_VERSION="4.03.0"
  - PACKAGE="dataloader" DISTRO="ubuntu-16.04" OCAML_VERSION="4.04.2"
  - PACKAGE="dataloader" DISTRO="ubuntu-16.04" OCAML_VERSION="4.05.0"
  - PACKAGE="dataloader" DISTRO="ubuntu-16.04" OCAML_VERSION="4.06.0"
  - PACKAGE="dataloader-lwt" DISTRO="ubuntu-16.04" OCAML_VERSION="4.03.0"
  - PACKAGE="dataloader-lwt" DISTRO="ubuntu-16.04" OCAML_VERSION="4.04.2"
  - PACKAGE="dataloader-lwt" DISTRO="ubuntu-16.04" OCAML_VERSION="4.05.0"
  - PACKAGE="dataloader-lwt" DISTRO="ubuntu-16.04" OCAML_VERSION="4.06.0"
